---
# Deploy a customized aJourney stack to a clustered layout.

- name:           Deploy the Wireguard server for the personal VLAN.
  hosts:          server
  become:         yes
  become_method:  sudo

  roles:
  - wireguard-server
